version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_1003Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/prabhakarsag
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/prabhakarsag
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.siqa_1003.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_1003Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1003.integrations:JMS_JNDI_SSL
  packages:
  - name: SIQA_1003Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: publisher:publisher
  packages:
  - name: SIQA_1003Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_1003.integrations:Sum
  packages:
  - name: SIQA_1003Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1003.integrations:deepclonetest
  packages:
  - name: SIQA_1003Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1003.integrations:tppdaf
  packages:
  - name: SIQA_1003Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
